#!/bin/bash

set -eux

export NODE_PATH=node_modules
#node build/src/main.js --worker_id=0 --controller=tcp://127.0.0.1:3333 --active_heartbeat_interval 1000
node build/src/main.js --worker_id=0 --controller=tcp://127.0.0.1:3333 --controller_aux=tcp://127.0.0.1:3335 --active_heartbeat_interval 1000
